from enum import Enum


class ErrCode(Enum):
    NORMAL = 0
    FAILED = -10
    NO_SUCH_CONDITION_INDEX = -11
    DISCORD_CONDITION_INDEX_NAME = -12
    CONDITION_REQUEST_EXCEED = -13
    USER_DATA_EXCHANGE_FAILED = -100
    SERVER_CONNECT_FAILED = -101
    VERSION_FAILED = -102
    LOCAL_FIREWALL_FAILED = -103
    MEMORY_PROTECTION_FAILED = -104
    FUNCTION_PARAMETER_ERROR = -105
    CONNECTION_ABORT = -106
    SECURITY_MODULE_ERROR = -107
    CERTIFICATE_LOGIN_NEEDED = -108

    DATA_REQUEST_EXCEED = -200
    PREAMBLE_INITIALIZE_FAILED = -201
    PREAMBLE_PARAMETER_ERROR = -202
    NO_DATA = -203
    STOCK_DATA_REQUEST_EXCEED = -204
    DATA_RECV_FAILED = 205
    FID_DATA_REQUEST_EXCEED = -206
    REALTIME_DATA_UNREG_ERROR = -207
    PRICE_INQUIRY_RESTRICTED = -209

    INPUT_VALUE_ERROR = -300
    NO_ACCOUNT_PASSWORD = -301
    BRROWED_NAME_ACCOUNT_ERROR = -302
